version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://test.onder.org.tr/api
    container_name: bilgeyaris-frontend
    restart: unless-stopped
    ports:
      - "7821:80"
    environment:
      - VITE_API_URL=https://test.onder.org.tr/api
    networks:
      - bilgeyaris-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bilgeyaris-backend
    restart: unless-stopped
    ports:
      - "7822:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=bilgeyaris_db
      - PORT=3000
      - JWT_SECRET=bilgeyaris-gizli-anahtar
      - JWT_EXPIRE=7d
    depends_on:
      - mysql
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    networks:
      - bilgeyaris-network

  mysql:
    image: mysql:8.0
    container_name: bilgeyaris-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=bilgeyaris_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "7823:3306"
    networks:
      - bilgeyaris-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bilgeyaris-phpmyadmin
    restart: unless-stopped
    ports:
      - "7824:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - bilgeyaris-network

networks:
  bilgeyaris-network:
    driver: bridge
volumes:
  mysql_data: